[package]
name = "winghost"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
eframe = { version = "0.31.1", default-features = false, features = ["glow", "wayland", "x11"] }
pty-windows = { path = "../../crates/pty-windows" }
renderer = { path = "../../crates/renderer" }
terminal-core = { path = "../../crates/terminal-core" }

[lints]
workspace = true
